/*
 * CryptoKit v1.0 /Examples.java
 * Last Updated: 12/08/2015 10:20PST
 * Description: This java file tests methods in the CryptoKit class.
 * Limitations: - Some methods only work with regex [^\w](alpha-numeric) values.
 *              - Keys must be generated by some other means (for now).
 * 
 * Happy encrypting!
 * @author ahmadsoomro.com
 */

public class CryptoKit {

    public static void main(String[] args) {
      //test bed
      //Testing transposition method:
       System.out.println(transposeString("Hello",1,5));
       
       //Testing substitution method:
       char[] key1 = {'H', 'l', '3', 'o', 'e'};
       char[] key2 = {'#', 'j', '4', 'i', '~'};
       System.out.println(substitutionString("Hello", key1, key2));
       
       //Testing the translate method
       String[] key3 = {"Yo", "whaz", "upnin"};
       String[] key4 = {"Hey", "what's", "up?"};
       System.out.println(translateString("Yo whaz upnin?", key3, key4));
       
       //Testing the inverse method
       System.out.println(inverse("Hello World"));
       
       //Testing the cypherstick
       System.out.println(cypherStick("Hello", 1));
       System.out.println(decypherStick("Hfexl@l7om", 1));
       
    }
}
